#!/usr/bin/env python

"""
ROS message source code generation for Java, from the command line.

Converts ROS .msg files in a package into Java source code implementations.
"""
import os
import sys

import genjava

if __name__ == "__main__":
    genjava.standalone_main(sys.argv)

